name: soundal
description: An Open Source Music Player App.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  app_links: ^6.3.1
  audio_service: ^0.18.9
  audiotagger: ^2.2.1
  # bitsdojo_window: ^0.1.1+1 #For Desktops
  cached_network_image: ^3.3.1
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.5
  dart_des: ^1.0.2
  device_info_plus: ^10.1.2
  file_picker: ^8.1.2
  flip_card: ^0.7.0
  flutter:
    sdk: flutter
  flutter_archive: ^6.0.3
  flutter_displaymode: ^0.6.0
  # flutter_downloader: ^1.7.1
  flutter_localizations:
    sdk: flutter
  flutter_lyric: ^2.0.4+6
  get_it: ^7.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  html_unescape: ^2.0.0
  isolate_manager: ^5.2.1
  just_audio: ^0.9.40
  # Discontinued, Use just_audio_windows instead.
  # just_audio_libwinmedia: ^0.0.4 # For windows and linux.
  logging: ^1.2.0
  material_design_icons_flutter: ^7.0.7296
  mutex: ^3.0.1
  metadata_god: ^0.5.2+1
  on_audio_query: ^2.9.0
  package_info_plus: ^8.0.2
  palette_generator: ^0.3.3+2
  path_provider: ^2.0.14
  permission_handler: ^11.3.1
  receive_sharing_intent: ^1.8.0
  salomon_bottom_bar: ^3.3.2
  share_plus: ^10.0.2
  sliding_up_panel: ^2.0.0+1
  url_launcher: ^6.1.10
  uuid: ^3.0.7
  youtube_explode_dart: ^2.2.1
  queue: ^3.1.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.1.2
  msix: ^3.7.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets to the application.
    - assets/

msix_config:
  display_name: Soundal
  publisher_display_name: Alvaro Rojas
  identity_name: com.arojas.soundal
  icons_background_color: transparent
  logo_path: assets/ic_launcher.png
  file_extension: .mp3, .m4a
